### ISSUE TITLE
Looking for collaborators?

### ISSUE THREAD

**Issue by sariths** [ksmet1977/luxpyOO#1]
Hi @ksmet1977 , are you planning to rewrite the luxpy repository? If you are looking for collaborators, I'd be happy to help.
Although it's not my specialization, I have some experience with Color Science and a fair amount of coding experience in Python on Open Source projects. I just finished my PhD from my Penn State where I studied with Dr. Kevin Houser.

**Comment by ksmet1977** [comment]
Hi Sarith,
I'm not sure yet, whether I'm going to rewrite it, as I'm not yet convinced
that it should. At the moment,  I'm just thinking of adding some class
functionality, but nothing more.
I'm currently working on a paper introducing the luxpy package, and I'd
like to get the version as it is out (at least after some further checking)
as soon as possible.
Anyway, thanks for volunteering to help on this project. Perhaps sometime
in the future, when I further extend it, or if I do decide to rewrite from
scratch.

best regards,
Kevin


2018-04-08 20:13 GMT+02:00 Sarith Subramaniam <notifications@github.com>:
